<div class="navbar pa">
    <a href="index.html" class="logo pa hd">SOP</a>
    <div class="nav_rt pa"></div>
    <!-- <ul class="n_rt">
        <li class="n3"><img src="images/avatar.jpg" alt=""><span>BIGONE</span><i>|</i><a href="javascript:;">SIGN OUT</a></li>
        <li class="n1"><a href="javascript:;">SIGN IN</a></li>
        <li class="n2"><a href="javascript:;">ENGLISH</a></li>
    </ul> -->
    <ul class="n_lf">
        <li><a href="index.html#news">NEWS</a><i>|</i></li>
        <li><a href="index.html#blog">DEV BLOGS</a><i>|</i></li>
        <li><a href="index.html#media">MEDIA</a></li>
    </ul>
</div>