<!-- 预注册 -->
<div class="tip pa" id="Pre_regi" style="display: none;">
    <div class="tip_title5 tip_title_bg">
        <a href="javascript:;" class="closebtn hd">关闭</a>
    </div>
    <div class="tip_cont">
         <div class="t2">
            <ul>
                <!-- 填写错误添加wrong样式 -->
                <li class="user"><span class="email_pop wrong" style="display: none;">Enter your email address</span><input class="tip_ico" type="text" value="Enter your email address" onblur="if(this.value=='')this.value='Enter your email address';$('.email_pop').hide()" onfocus="if(this.value=='Enter your email address')this.value='';$('.email_pop').show()"></li>
                <li><div class="agreebtn3 pa"><span></span><a href="#" target="_blank">Terms and condition</div></li>
            </ul>
            <div class="tipbtnbar">
                <a href="javascript:;" id="pre_submit" class="submitbtn2 tip_btn_bg hd">SUBMIT</a>
            </div>
         </div>
    </div>
</div>
<!-- 预注册完成 -->
<div class="tip pa" id="pre_regi_done" style="display: none;">
    <div class="tip_cont">
        <div class="t5">
            <div class="donetxt tip_btn_bg hd">You are all set!</div>
            <div class="donetxt_small">You have subscribed Synced: Off-Planet news feed.</div>
            <a href="javascript:;" id="backbtn" class="backbtn tip_btn_bg hd">back to main page</a>
            <div class="djs">[<span>10</span>s]</div>
        </div>
    </div>
</div>

<!-- 登录 -->
<div class="tip pa" id="sign" style="display: none;">
    <div class="tip_title1 tip_title_bg">
        <a href="javascript:;" class="closebtn hd">关闭</a>
    </div>
    <div class="tip_cont">
         <div class="t1">
            <ul>
                <li class="user"><input class="tip_ico" type="text" value="Your email address" onblur="if(this.value=='')this.value='Your email address'" onfocus="if(this.value=='Your email address')this.value=''">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Or click on your activation link received from your mail box.Or click on your activation link received from your mail box.
                            </div>
                        </div>
                    </a>
                </li>
                <li class="password"><input class="tip_ico" type="text" value="Your password" onblur="if(this.value=='')this.value='Your password'" onfocus="if(this.value=='Your password')this.value=''"></li>
                <li><a href="javascript:;" class="forget">Forgot your password?</a><div class="agreebtn2 pa"><span></span><a href="#" target="_blank">Terms and condition</div></li>
            </ul>
            <div class="tipbtnbar">
                <a href="javascript:;" class="accountbtn tip_btn_bg hd">Do not have an account yet?</a>
                <a href="javascript:;" class="loginbtn tip_btn_bg hd">Login</a>
            </div>
         </div>
    </div>
</div>
<!-- 注册 -->
<div class="tip pa" id="account" style="display: none;">
    <div class="tip_title2 tip_title_bg">
        <a href="javascript:;" class="closebtn hd">关闭</a>
    </div>
    <div class="tip_cont">
         <div class="t2">
            <ul>
                <li class="user"><input class="tip_ico" type="text" value="Account" onblur="if(this.value=='')this.value='Account'" onfocus="if(this.value=='Account')this.value=''">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Or click on your activation link received from your mail box.Or click on your activation link received from your mail box.
                            </div>
                        </div>
                    </a>
                    <i class="yes_n tip_ico"></i>
                </li>
                <li class="password"><input class="tip_ico" type="text" value="Password" onblur="if(this.value=='')this.value='Password'" onfocus="if(this.value=='Password')this.value=''">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Or click on your activation link received from your mail box.
                            </div>
                        </div>
                    </a>
                    <i class="no_n tip_ico"></i>
                </li>
                <li class="password"><input class="tip_ico" type="text" value="Please confirm password" onblur="if(this.value=='')this.value='Please confirm password'" onfocus="if(this.value=='Please confirm password')this.value=''"></li>
            </ul>
            <div class="tipbtnbar">
                <a href="javascript:;" class="sendbtn tip_btn_bg hd">Send Verifed Code and Link to Email</a>
            </div>
            <ul>
                <li class="code">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Or click on your activation link received from your mail box.
                            </div>
                        </div>
                    </a>
                    <input class="tip_ico" type="text" value="Please fill in your activation code" onblur="if(this.value=='')this.value='Please fill in your activation code'" onfocus="if(this.value=='Please fill in your activation code')this.value=''">
                </li>
            </ul>
            <div class="tipbtnbar">
                <a href="javascript:;" class="submitbtn2 tip_btn_bg hd">SUBMIT</a>
            </div>
         </div>
    </div>
</div>
<!-- 找回密码 -->
<div class="tip pa" id="reget" style="display: none;">
    <div class="tip_title3 tip_title_bg">
        <a href="javascript:;" class="closebtn hd">关闭</a>
    </div>
    <div class="tip_cont">
         <div class="t3">
            <ul>
                <li class="user"><input class="tip_ico" type="text" value="Your email address" onblur="if(this.value=='')this.value='Your email address'" onfocus="if(this.value=='Your email address')this.value=''">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Or click on your activation link received from your mail box.
                            </div>
                        </div>
                    </a>
                    <i class="yes_n tip_ico"></i>
                    <a href="javascrript:;" class="verifbtn tip_btn_bg pa">
                        <img src="images/sendvericode.png" alt="">
                        <span>[<em>59</em>s]</span>
                    </a>
                </li>
                <li class="code">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Or click on your activation link received from your mail box.
                            </div>
                        </div>
                    </a>
                    <input class="tip_ico" type="text" value="Please enter your verification code in your email address" onblur="if(this.value=='')this.value='Please enter your verification code in your email address'" onfocus="if(this.value=='Please enter your verification code in your email address')this.value=''">
                </li>
            </ul>
            <div class="tipbtnbar">
                <a href="javascript:;" class="submitbtn2 tip_btn_bg hd">SUBMIT</a>
            </div>
         </div>
    </div>
</div>
<!-- 重置密码 -->
<div class="tip pa" id="reset" style="display: none;">
    <div class="tip_title2 tip_title_bg">
        <a href="javascript:;" class="closebtn hd">关闭</a>
    </div>
    <div class="tip_cont">
         <div class="t4">
            <ul>
                <li class="user"><input class="tip_ico" type="text" value="Account" onblur="if(this.value=='')this.value='Account'" onfocus="if(this.value=='Account')this.value=''">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Or click on your activation link received from your mail box.Or click on your activation link received from your mail box.
                            </div>
                        </div>
                    </a>
                    <i class="yes_n tip_ico"></i>
                </li>
                <li class="password"><input class="tip_ico" type="text" value="New password" onblur="if(this.value=='')this.value='New password'" onfocus="if(this.value=='New password')this.value=''">
                    <a href="javscript:;" class="gt tip_ico">
                        <div class="popbar">
                            <div class="popbar_top tip_btn_bg"></div>
                            <div class="popbar_bottom tip_btn_bg">
                                Please enter your new password. Please include at least 1 uppercase, 1 lowercase, and 1 number, with a minimum of 10 characters.
                            </div>
                        </div>
                    </a>
                    <i class="no_n tip_ico"></i>
                </li>
                <li class="password"><input class="tip_ico" type="text" value="Confirm your new password" onblur="if(this.value=='')this.value='Confirm your new password'" onfocus="if(this.value=='Confirm your new password')this.value=''"></li>
            </ul>
            <div class="tipbtnbar">
                <a href="javascript:;" class="submitbtn2 tip_btn_bg hd">SUBMIT</a>
            </div>
         </div>
    </div>
</div>
<!-- 注册完成 -->
<div class="tip pa" id="account_done" style="display: none;">
    <div class="tip_cont">
        <div class="t5">
            <div class="donetxt tip_btn_bg hd">You are all set!</div>
            <a href="javascript:;" id="backbtn" class="backbtn tip_btn_bg hd">back to main page</a>
            <div class="djs">[<span>10</span>s]</div>
        </div>
    </div>
</div>
<!-- media视频图片弹窗 -->
<div class="pop" id="m_pop">
    <a href="javascript:;" class="closebtn2 hd"></a>
    <div class="med_body"></div>
</div>
