<div class="copytright">
    <p class="at">Age Tags and other games</p>
    <ul class="sns">
        <li><a href="javascript:;" class="s1"></a></li>
        <li><a href="javascript:;" class="s2"></a></li>
        <li><a href="javascript:;" class="s3"></a></li>
        <li><a href="javascript:;" class="s4"></a></li>
        <li><a href="javascript:;" class="s5"></a></li>
    </ul>
    <ul class="links">
        <li><a href="">Customer Service</a></li>|
        <li><a href="">Terms of Use</a></li>|
        <li><a href="">Privacy</a></li>|
        <li><a href="">Partnership Inquiry</a></li>
    </ul>
    <p class="cr">Copyright ? 2020 Tencent. All Rights Reserved</p>
</div>