<div class="topbar">
        <a href="index.html" class="logo hd">SOP</a>
        <div id="btnNavSlide" class="btn_nav_slide"><i class="draw" title="µ¼º½¿ª¹Ø"></i></div>
        <nav id="commonNav" class="common_nav o_h">
            <div class="cover_content">
                <!-- <ul class="pop_bar1">
                    <li><a href="javascript:;" id="signin">SIGN IN</a></li>
                    <li class="signed"><img src="images/avatar.jpg" alt=""><span>BIGONE</span><i>|</i><a href="javascript:;">SIGN OUT</a></li>
                </ul> -->
                <ul class="pop_links">
                    <li><a href="index.html#news">NEWS</a><i></i></li>
                    <li><a href="index.html#blog">DEV BLOGS</a><i></i></li>
                    <li><a href="index.html#media">MEDIA</a></li>
                </ul>
                <!-- <ul class="pop_bar2">
                    <li><a href="javascript:;">ENGLISH</a></li>
                </ul> -->
            </div>
        </nav>
    </div>