<!-- 预注册 -->
<div class="tip pa" id="pre_regi" style="display: none;">
    <a href="javascript:;" class="backbtn pa hd"></a>
    <div class="tip_cont2">
        <h2>Pre-register</h2>
        <ul>
            <li class="user"><input class="tip_ico" type="text" value="Your account / email address" onblur="if(this.value=='')this.value='Your account / email address'" onfocus="if(this.value=='Your account / email address')this.value=''">
            </li>
            <li class="condi"><span class="wrong">Provide correct e-mail address</span><div class="agreebtn3 pa"><span></span><a href="#">Terms and condition</a></div></li>
        </ul>
        <div class="tipbtnbar">
            <a href="javascript:;" class="submitbtn2 tip_btn_bg hd" id="pre_submit">SUBMIT</a>
        </div>
    </div>
</div>
<!-- 预注册完成 -->
<div class="tip pa" id="pre_regi_done" style="display: none;">
    <a href="javascript:;" class="backbtn pa hd"></a>
    <div class="tip_cont3">
        <div class="donetxt">You are all set!</div>
        <div class="donetxt_small">You have subscribed Synced: Off-Planet news feed.</div>
        <a href="javascript:;" id="pre_back" class="back tip_btn_bg hd">back to main page</a>
        <div class="djs">[<span>10</span>s]</div>
    </div>
</div>

<!-- 登录 -->
<div class="tip" id="sign" style="display: none;">
    <a href="javascript:;" class="backbtn pa hd"></a>
    <div class="tip_cont">
        <h2>Sign in</h2>
        <ul>
            <li class="user"><input class="tip_ico" type="text" value="Your email address" onblur="if(this.value=='')this.value='Your email address'" onfocus="if(this.value=='Your email address')this.value=''">
                
            </li>
            <li class="password"><input class="tip_ico" type="text" value="Your password" onblur="if(this.value=='')this.value='Your password'" onfocus="if(this.value=='Your password')this.value=''"></li>
            <li class="qx"><a href="javascript:;" class="forget">Forgot your password?</a><div class="agreebtn2 pa"><span></span><a href="#">Terms and condition</a></div></li>
        </ul>
        <div class="tipbtnbar">
            <a href="javascript:;" class="loginbtn tip_btn_bg hd">Login</a>
            <a href="javascript:;" class="accountbtn tip_btn_bg hd">Creat an account</a>
        </div>
    </div>
</div>
<!-- 注册 -->
<div class="tip" id="account" style="display: none;">
    <a href="javascript:;" class="backbtn pa hd"></a>
    <div class="tip_cont2">
        <h2>Sign up</h2>
        <ul>
            <li class="user"><input class="tip_ico" type="text" value="Your account / email address" onblur="if(this.value=='')this.value='Your account / email address'" onfocus="if(this.value=='Your account / email address')this.value=''">
            </li>
            <li class="password"><input class="tip_ico" type="text" value="Your password" onblur="if(this.value=='')this.value='Your password'" onfocus="if(this.value=='Your password')this.value=''"></li>
            <div class="tsinfo">Please include at least 1 uppercase, 1 lowercase, and 1 number, with a minimum of 10 characters. </div>
            <li class="password"><input class="tip_ico" type="text" value="Please confirm your password" onblur="if(this.value=='')this.value='Please confirm your password'" onfocus="if(this.value=='Please confirm your password')this.value=''"></li>
        </ul>
        <div class="tipbtnbar">
            <a href="javascript:;" class="sendbtn tip_btn_bg hd">Send Verifed Code and Link to Email</a>
        </div>
        <ul style="margin-bottom: 1rem;">
            <li class="code"><input class="tip_ico" type="text" value="Please fill in your activation code" onblur="if(this.value=='')this.value='Please fill in your activation code'" onfocus="if(this.value=='Please fill in your activation code')this.value=''">
                <i class="yes_n tip_ico"></i>
            </li>
            <div class="tsinfo">Or click on your activation link received from your mail box.</div>
        </ul>
        <div class="tipbtnbar">
            <a href="javascript:;" class="submitbtn2 tip_btn_bg hd">SUBMIT</a>
        </div>
    </div>
</div>
<!-- 找回密码 -->
<div class="tip" id="reget" style="display: none;">
    <a href="javascript:;" class="backbtn pa hd"></a>
    <div class="tip_cont2">
        <h2>Reset my password</h2>
        <ul>
            <li class="user"><input class="tip_ico" type="text" value="Your account / email address" onblur="if(this.value=='')this.value='Your account / email address'" onfocus="if(this.value=='Your account / email address')this.value=''">
            </li>
        </ul>
        <div class="tipbtnbar">
            <a href="javascrript:;" class="verifbtn tip_btn_bg">Send verification code
                <span>[<em>59</em>s]</span>
            </a>
        </div>
        <ul style="margin-bottom: 1rem;">
            <li class="code"><input class="tip_ico" type="text" value="Your verification code" onblur="if(this.value=='')this.value='Your verification code'" onfocus="if(this.value=='Your verification code')this.value=''">
                <i class="no_n tip_ico"></i>
            </li>
            <div class="tsinfo">Please include at least 1 uppercase, 1 lowercase, and 1 number, with a minimum of 10 characters. </div>
        </ul>
        <div class="tipbtnbar">
            <a href="javascript:;" class="submitbtn2 tip_btn_bg hd">SUBMIT</a>
        </div>
    </div>
</div>
<!-- 重置密码 -->
<div class="tip" id="reget" style="display: none;">
    <a href="javascript:;" class="backbtn pa hd"></a>
    <div class="tip_cont">
        <h2>Renew my password</h2>
        <ul>
            <li class="user"><input class="tip_ico" type="text" value="Your account / email address" onblur="if(this.value=='')this.value='Your account / email address'" onfocus="if(this.value=='Your account / email address')this.value=''">
            </li>
            <li class="password"><input class="tip_ico" type="text" value="New password" onblur="if(this.value=='')this.value='New password'" onfocus="if(this.value=='New password')this.value=''">
                <i class="no_n tip_ico"></i>
            </li>
            <li class="password"><input class="tip_ico" type="text" value="Please confirm your password" onblur="if(this.value=='')this.value='Please confirm your password'" onfocus="if(this.value=='Please confirm your password')this.value=''">
                <i class="yes_n tip_ico"></i>
            </li>
        </ul>
        <div class="tipbtnbar">
            <a href="javascript:;" class="submitbtn3 tip_btn_bg hd">SUBMIT</a>
        </div>
    </div>
</div>
<!-- 注册完成 -->
<div class="tip pa" id="account_done" style="display: none;">
    <a href="javascript:;" class="backbtn pa hd"></a>
    <div class="tip_cont">
        <div class="donetxt">You are all set!</div>
        <a href="javascript:;" id="back" class="back tip_btn_bg hd">back to main page</a>
        <div class="djs">[<span>10</span>s]</div>
    </div>
</div>
<!-- media视频图片弹窗 -->
<div class="pop" id="m_pop">
    <a href="javascript:;" class="closebtn2 hd"></a>
    <div class="med_body"></div>
</div>